Install hook
canonical/mongos-operator pull request #3
Opened 2023-11-21 19:07 UTC by MiaAltieri

2023-11-21 19:09 UTC, MiaAltieri commented on src/config.py
> +"""Configuration for MongoDB Charm."""
copied and editted from MongoDB-operator

2023-11-21 19:10 UTC, MiaAltieri commented on src/exceptions.py
> +#!/usr/bin/env python3
copied from MongoDB-operator

2023-11-21 19:11 UTC, MiaAltieri commented on src/machine_helpers.py
> +"""Machine Charm specific functions for operating MongoDB."""
copied from mongodb-operator and removed functions

2023-11-21 19:11 UTC, MiaAltieri commented on src/charm.py
> +                )
copied from MongoDB operator

2023-11-22 10:27 UTC, dmitry-ratushnyy commented on src/charm.py
> +            self.unit.status = BlockedStatus("Could not install mongos")
Maybe we can update the message to a user, because here we are failing on opening file, not on installing mongos, so the message is a bit misleading

2023-11-22 12:25 UTC, delgod requested changes

2023-11-22 12:25 UTC, delgod commented on metadata.yaml
> +    location: /var/snap/charmed-mongodb/common
I don't think mongos itself needs storage. do we need this?

2023-11-22 12:25 UTC, delgod commented on requirements.txt
> +attrs==22.2.0
Can we start using poetry from the very beginning?

2023-11-27 20:04 UTC, dmitry-ratushnyy commented on .gitignore
> +requirements.txt
nits: new line :)

2023-11-27 20:06 UTC, dmitry-ratushnyy approved these changes

2023-11-28 17:05 UTC, delgod approved these changes

2023-11-28 17:15 UTC, merged